apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: lynx-eventlistener-route
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-lynx-eventlistener
    weight: 100