apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: lynx-pipeline-triggerbinding
spec:
  params:
    - name: namespace
      value: lynx-dev
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: gitrepositoryname
      value: $(body.repository.name)