apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: lynx-frontend-run-
spec:
  serviceAccountName: lynx-build-bot
  pipelineRef:
    name: lynx-pipeline
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: lynx-pvc
